name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-client ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-server ./server
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-worker ./worker

      - run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-client
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-nginx
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-server
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-multicontainer-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multicontainer
          environment_name: Docker-multicontainer-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-146463422607
          region: eu-north
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
